bender:
    # Publish all joint states -----------------------------------
    joint_state_controller:
        type: "joint_state_controller/JointStateController"
        publish_rate: 30

    # Controller for independent wheels --------------------------
    swerve_controller:
        type: "swerve_controller/SwerveController"
        
        # Joints
        lf_wheel: "wheel_lf_joint"
        rf_wheel: "wheel_rf_joint"
        lh_wheel: "wheel_lh_joint"
        rh_wheel: "wheel_rh_joint"
        lf_steering: "leg_lf_joint"
        rf_steering: "leg_rf_joint"
        lh_steering: "leg_lh_joint"
        rh_steering: "leg_rh_joint"

        # Range of motion of steering motors
        max_steering_angle: 1.58
        min_steering_angle: -1.58

        # Other
        publish_rate: 30
        enable_odom_tf: false
        enable_min_steering_difference: false
        pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
        twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
        cmd_vel_timeout: 0.5
        base_frame_id: "base_footprint"

        # Limiters
        linear:
          x:
            has_velocity_limits: true
            has_acceleration_limits: true
            max_velocity: 0.7
            min_velocity: -0.7
            max_acceleration: 5.0
            min_acceleration: -5.0
        angular:
          z:
            has_velocity_limits: true
            has_acceleration_limits: true
            max_velocity: 0.785
            min_velocity: -0.785
            max_acceleration: 6.28
            min_acceleration: -6.28

        # Geometry (Do not provide the following if you want it to be parsed in the URDF)
        # track: 0.8
        # wheel_steering_y_offset: 0
        # wheel_radius: 0.15
        # wheel_base: 1.2
